ConnectionStrings: 
    PolicyConnection: Data Source=microservices.demo.policy.db;Initial Catalog=Microservices.Demo.Policy;Persist Security Info=True;User ID=sa;Password=Password1234
ServicesUrl:
    PricingApiUrl: https://Microservices.Demo.Pricing.API/api/pricing  
